#!/usr/bin/env python3
"""papertrail model profile — parse plans/model-profile.md and generate
project review agents in .claude/agents/. Stdlib only.

Subcommands:
    stage <key>   print one stage's row as JSON (empty output = no profile or
                  no usable row; parse warnings go to stderr)
    generate      write pt-*.md agent files from the profile (ownership-marked,
                  checksum-stamped; refuses same-named files without the marker)
    check         print a one-line hint when generated agents are stale
                  against the current profile
"""
import argparse
import hashlib
import json
import os
import re
import stat
import sys
import tempfile
from pathlib import Path

STAGE_LABELS = {
    "plan": "plan",
    "execute": "execute",
    "sync": "sync",
    "plan review": "plan-review",
    "results validation": "results-validation",
    "board reviewer panel": "board-reviewer",
}
MODEL_ALIASES = {"inherit", "opus", "sonnet", "haiku", "fable"}
MODEL_ID_RE = re.compile(r"^claude-[a-z0-9.-]+$")
EFFORT_LEVELS = {"low", "medium", "high", "xhigh", "max"}
NO_EFFORT = {"", "-", "—", "–"}  # blank, hyphen, em dash, en dash
MECHANISMS = {"nudge", "agent"}
AGENT_STAGES = {
    "plan-review": "pt-plan-reviewer",
    "results-validation": "pt-results-validator",
    "board-reviewer": "pt-board-reviewer",
}
# The mechanism each stage is expected to carry in a canonical profile. The
# board edits model/effort only and never touches mechanism, so a file whose
# mechanism mapping drifts from this is treated as non-canonical (CLI-only).
EXPECTED_MECHANISM = {
    "plan": "nudge",
    "execute": "nudge",
    "sync": "nudge",
    "plan-review": "agent",
    "results-validation": "agent",
    "board-reviewer": "agent",
}
MARKER_RE = re.compile(
    # Ownership marker stamped into every generated agent file. group(1) is
    # the profile checksum. An unrecognized marker makes an owned file read
    # as user-owned and refuse regeneration.
    r"<!-- generated by papertrail /models · profile sha256:([0-9a-f]{64}) -->"
)
MISMATCH_HINT = (
    "review agents are out of date with the installed plugin or profile — "
    "run /papertrail:models and regenerate"
)
PROFILE_REL = Path("plans") / "model-profile.md"


def find_root(start=None):
    p = Path(start if start else Path.cwd()).resolve()
    for cand in (p, *p.parents):
        if (cand / "plans" / "master-plan.md").exists():
            return cand
    return p


def _norm(cell):
    return re.sub(r"\s+", " ", re.sub(r"\([^)]*\)", "", cell).strip().lower())


def _row_cells(line):
    s = line.strip()
    if not s.startswith("|"):
        return None
    return [c.strip() for c in s.strip("|").split("|")]


def _add_row(stages, warnings, cells, rownum):
    if len(cells) != 4:
        warnings.append(
            f"model-profile: skipping row {rownum} (expected 4 cells, got {len(cells)})"
        )
        return
    raw_stage, raw_model, raw_effort, raw_mech = cells
    key = STAGE_LABELS.get(_norm(raw_stage))
    if key is None:
        warnings.append(f"model-profile: skipping row {rownum} (unknown stage {raw_stage!r})")
        return
    if key in stages:
        warnings.append(f"model-profile: skipping row {rownum} (duplicate stage {raw_stage!r})")
        return
    model = raw_model.strip().lower()
    if model not in MODEL_ALIASES and not MODEL_ID_RE.match(model):
        warnings.append(f"model-profile: skipping row {rownum} (unknown model {raw_model!r})")
        return
    effort = raw_effort.strip().lower()
    if effort in NO_EFFORT:
        effort = None
    elif effort not in EFFORT_LEVELS:
        warnings.append(f"model-profile: skipping row {rownum} (unknown effort {raw_effort!r})")
        return
    mech = raw_mech.strip().lower()
    if mech not in MECHANISMS:
        warnings.append(
            f"model-profile: skipping row {rownum} (unknown mechanism {raw_mech!r})"
        )
        return
    stages[key] = {"stage": key, "model": model, "effort": effort, "mechanism": mech}


def parse_profile(text):
    """Return (stages, warnings). Strict: malformed rows are warned and skipped."""
    stages, warnings = {}, []
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        cells = _row_cells(lines[i])
        if cells is not None and [_norm(c) for c in cells] == ["stage", "model", "effort", "mechanism"]:
            i += 1
            if i < len(lines):
                sep = _row_cells(lines[i])
                if sep is not None and set("".join(sep)) <= set("-: "):
                    i += 1
            rownum = 0
            while i < len(lines):
                cells = _row_cells(lines[i])
                if cells is None:
                    break
                rownum += 1
                _add_row(stages, warnings, cells, rownum)
                i += 1
            break
        i += 1
    if not stages and not warnings:
        warnings.append("model-profile: no stage/model/effort/mechanism table found")
    return stages, warnings


def load_profile(root):
    """Return (stages, warnings, exists)."""
    path = root / PROFILE_REL
    if not path.exists():
        return {}, [], False
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return {}, ["model-profile: unreadable (not UTF-8 or IO error)"], True
    stages, warnings = parse_profile(text)
    return stages, warnings, True


def profile_canonical(stages, warnings):
    """True iff the profile is safe for inline board editing: no parse
    warnings, exactly the six canonical stages, each with its expected
    mechanism. A hand-edited file (missing/extra row, flipped mechanism,
    trailing junk that warns) is non-canonical and must be edited via the CLI,
    not the board — editing it there could delete a marked agent."""
    if warnings:
        return False
    if set(stages) != set(STAGE_LABELS.values()):
        return False
    return all(stages[k]["mechanism"] == EXPECTED_MECHANISM[k] for k in stages)


def locate_table(text):
    """Locate the profile table. Return (header_idx, first_data_idx,
    last_data_idx) as indices into text.splitlines(keepends=True), inclusive of
    the data range, or None when there is no stage/model/effort/mechanism table
    or it has zero data rows. Mirrors parse_profile's scan so both agree."""
    lines = text.splitlines(keepends=True)
    i = 0
    while i < len(lines):
        cells = _row_cells(lines[i])
        if cells is not None and [_norm(c) for c in cells] == ["stage", "model", "effort", "mechanism"]:
            header_idx = i
            i += 1
            if i < len(lines):
                sep = _row_cells(lines[i])
                if sep is not None and set("".join(sep)) <= set("-: "):
                    i += 1
            first = i
            while i < len(lines) and _row_cells(lines[i]) is not None:
                i += 1
            last = i - 1
            if last < first:
                return None
            return (header_idx, first, last)
        i += 1
    return None


def rewrite_rows(base_text, edits):
    """Return base_text with only the model/effort cells of the data rows named
    in `edits` overwritten. `edits` maps a canonical stage key ->
    {"model": str, "effort": str|None}. Label and mechanism cells are kept
    verbatim, and every byte outside the table's data rows is untouched (line
    endings preserved). Raises ValueError if the table can't be located."""
    loc = locate_table(base_text)
    if loc is None:
        raise ValueError("no profile table to rewrite")
    _, first, last = loc
    lines = base_text.splitlines(keepends=True)
    for idx in range(first, last + 1):
        line = lines[idx]
        ending = line[len(line.rstrip("\r\n")):]
        cells = _row_cells(line)
        if cells is None or len(cells) != 4:
            continue
        key = STAGE_LABELS.get(_norm(cells[0]))
        if key is None or key not in edits:
            continue
        model = edits[key]["model"]
        effort = edits[key]["effort"]
        eff = "—" if effort is None else effort
        lines[idx] = "| " + " | ".join([cells[0], model, eff, cells[3]]) + " |" + ending
    return "".join(lines)


def profile_view(text):
    """Structured view of a profile's text for the board: canonical rows in
    stage order (with the verbatim display label), the prose slices around the
    table, editability, and any parse warnings. board.py wraps this with
    path/exists/baselineHash/agentsGitignored."""
    stages, warnings = parse_profile(text)
    loc = locate_table(text)
    lines = text.splitlines(keepends=True)
    raw_labels = {}
    if loc is None:
        prose_before, prose_after = text, ""
    else:
        header_idx, first, last = loc
        prose_before = "".join(lines[:header_idx])
        prose_after = "".join(lines[last + 1:])
        for idx in range(first, last + 1):
            cells = _row_cells(lines[idx])
            if cells and len(cells) == 4:
                k = STAGE_LABELS.get(_norm(cells[0]))
                if k is not None:
                    raw_labels.setdefault(k, cells[0])
    rows = []
    for key in STAGE_LABELS.values():
        row = stages.get(key)
        if row is None:
            continue
        rows.append({
            "stage": key,
            "label": raw_labels.get(key, key),
            "model": row["model"],
            "effort": row["effort"],
            "mechanism": row["mechanism"],
        })
    return {
        "rows": rows,
        "proseBefore": prose_before,
        "proseAfter": prose_after,
        "editable": profile_canonical(stages, warnings),
        "warnings": warnings,
    }


def cmd_stage(root, key):
    stages, warnings, exists = load_profile(root)
    if not exists:
        return 0
    for w in warnings:
        print(w, file=sys.stderr)
    row = stages.get(key)
    if row:
        print(json.dumps(row))
    return 0


def _templates_dir():
    return Path(__file__).resolve().parents[1] / "templates" / "agents"


def _render(template_text, model, effort, checksum):
    out = template_text
    if effort is None:
        out = re.sub(r"^effort: \{\{EFFORT\}\}\n", "", out, flags=re.M)
    else:
        out = out.replace("{{EFFORT}}", effort)
    return out.replace("{{MODEL}}", model).replace("{{CHECKSUM}}", checksum)


def _strip_marker(text):
    """Replace the checksum inside the ownership marker so two renders differing
    only by their profile-sha256 stamp compare equal (a checksum-only change
    does not alter an agent's runtime behavior)."""
    return MARKER_RE.sub("<!-- MARKER -->", text)


def atomic_write(target, text):
    """Write text to target atomically: a uniquely-named temp file beside the
    target, then os.replace. The existing file's permission bits are preserved
    (new files default to 0644). The temp is cleaned up on any error."""
    mode = stat.S_IMODE(target.stat().st_mode) if target.exists() else 0o644
    fd, tmpname = tempfile.mkstemp(dir=str(target.parent), prefix=target.name + ".", suffix=".tmp")
    try:
        # newline="" disables translation: the text already carries the exact
        # line endings we want (the byte-splice preserves the source's), so a
        # text-mode \n->\r\n rewrite on Windows would double CRLF into CRCRLF.
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as f:
            f.write(text)
        os.chmod(tmpname, mode)
        os.replace(tmpname, target)
    except BaseException:
        try:
            os.unlink(tmpname)
        except OSError:
            pass
        raise


def _remove_if_marked(target, rel, key, stdout):
    """Delete target if it exists and carries the ownership marker. Appends any
    message to `stdout`. Returns an outcome: "removed", "refused-unreadable",
    "absent" (nothing there), or "absent-user" (a user-owned file left alone)."""
    if not target.exists():
        return "absent"
    try:
        existing = target.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        stdout.append(f"refused (unreadable): {rel}")
        return "refused-unreadable"
    if not MARKER_RE.search(existing):
        return "absent-user"
    target.unlink()
    stdout.append(f"removed stale {rel} (no usable '{key}' agent row in the profile)")
    return "removed"


def generate(root):
    """Regenerate the pt-* agents from the profile without printing. Returns a
    dict the caller renders and/or inspects:

        {"code": int,              # 0 ok, 1 no-profile / unreadable
         "stdout": [str], "stderr": [str],   # exact CLI lines, per stream
         "results": [{"agent","stage","outcome"}],
         "restartNeeded": bool, "changedStages": [str]}

    Outcomes: created, runtimeChanged, checksumOnlyChanged, unchanged,
    refused-user, refused-unreadable, removed, absent, absent-user. A session
    restart is needed iff any agent was created, its runtime definition
    (frontmatter/body, not just the checksum stamp) changed, or it was removed.
    Agent files are written atomically."""
    path = root / PROFILE_REL
    stdout, stderr, results = [], [], []
    fail = {"code": 1, "stdout": stdout, "stderr": stderr, "results": results,
            "restartNeeded": False, "changedStages": []}
    if not path.exists():
        stderr.append(f"models.py: no {PROFILE_REL} — nothing to generate")
        return fail
    try:
        data = path.read_bytes()
    except OSError:
        stderr.append("model-profile: unreadable (not UTF-8 or IO error) — nothing generated")
        return fail
    checksum = hashlib.sha256(data).hexdigest()
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        stderr.append("model-profile: unreadable (not UTF-8 or IO error) — nothing generated")
        return fail
    stages, warnings = parse_profile(text)
    stderr.extend(warnings)
    agents_dir = root / ".claude" / "agents"
    dir_existed = agents_dir.is_dir()
    wrote_any = False
    for key, agent in AGENT_STAGES.items():
        rel = f".claude/agents/{agent}.md"
        target = agents_dir / f"{agent}.md"
        row = stages.get(key)
        if row is None:
            stderr.append(f"model-profile: no valid '{key}' row — {agent}.md not regenerated")
            outcome = _remove_if_marked(target, rel, key, stdout)
            results.append({"agent": agent, "stage": key, "outcome": outcome})
            continue
        if row["mechanism"] != "agent":
            stderr.append(
                f"model-profile: '{key}' row has mechanism '{row['mechanism']}' — {agent}.md not regenerated"
            )
            outcome = _remove_if_marked(target, rel, key, stdout)
            results.append({"agent": agent, "stage": key, "outcome": outcome})
            continue
        old = None
        if target.exists():
            try:
                old = target.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                stdout.append(f"refused (unreadable): {rel}")
                results.append({"agent": agent, "stage": key, "outcome": "refused-unreadable"})
                continue
            if not MARKER_RE.search(old):
                stdout.append(f"refused (user-owned, no marker): {rel}")
                results.append({"agent": agent, "stage": key, "outcome": "refused-user"})
                continue
        try:
            template = (_templates_dir() / f"{agent}.md").read_text(encoding="utf-8")
            rendered = _render(template, row["model"], row["effort"], checksum)
            agents_dir.mkdir(parents=True, exist_ok=True)
            atomic_write(target, rendered)
        except (OSError, UnicodeDecodeError) as e:
            stderr.append(f"model-profile: could not write {rel} ({e})")
            results.append({"agent": agent, "stage": key, "outcome": "error"})
            continue
        stdout.append(f"wrote {rel}")
        wrote_any = True
        if old is None:
            outcome = "created"
        elif _strip_marker(old) != _strip_marker(rendered):
            outcome = "runtimeChanged"
        elif old != rendered:
            outcome = "checksumOnlyChanged"
        else:
            outcome = "unchanged"
        results.append({"agent": agent, "stage": key, "outcome": outcome})
    if wrote_any and not dir_existed:
        stdout.append("note: .claude/agents/ was just created — restart Claude Code before the new agents can be dispatched")
    changed = [r["stage"] for r in results if r["outcome"] in ("created", "runtimeChanged", "removed")]
    return {"code": 0, "stdout": stdout, "stderr": stderr, "results": results,
            "restartNeeded": bool(changed), "changedStages": changed}


def cmd_generate(root):
    res = generate(root)
    for line in res["stdout"]:
        print(line)
    for line in res["stderr"]:
        print(line, file=sys.stderr)
    return res["code"]


def cmd_check(root):
    path = root / PROFILE_REL
    if not path.exists():
        return 0
    try:
        data = path.read_bytes()
    except OSError:
        return 0
    checksum = hashlib.sha256(data).hexdigest()
    try:
        stages, _ = parse_profile(data.decode("utf-8"))
    except UnicodeDecodeError:
        stages = {}
    for key, agent in AGENT_STAGES.items():
        target = root / ".claude" / "agents" / f"{agent}.md"
        if not target.exists():
            continue
        try:
            text = target.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        m = MARKER_RE.search(text)
        if not m:
            continue  # user-owned — never hint about files we don't manage
        if m.group(1) != checksum:
            print(MISMATCH_HINT)
            return 0
        row = stages.get(key)
        if row is None or row["mechanism"] != "agent":
            # generate() would REMOVE this marked agent — that is drift too.
            # Report it without rendering a template for a nonexistent row.
            print(MISMATCH_HINT)
            return 0
        try:
            template = (_templates_dir() / f"{agent}.md").read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        rendered = _render(template, row["model"], row["effort"], checksum)
        if _strip_marker(text) != _strip_marker(rendered):
            # The shipped template changed since this agent was generated —
            # the profile checksum alone cannot see this.
            print(MISMATCH_HINT)
            return 0
    return 0


def main(argv=None):
    ap = argparse.ArgumentParser(description="papertrail model profile tools")
    ap.add_argument("--root", default=None, help="project root (default: walk up to plans/master-plan.md)")
    sub = ap.add_subparsers(dest="cmd", required=True)
    p_stage = sub.add_parser("stage", help="print one stage's profile row as JSON")
    p_stage.add_argument("key", choices=sorted(set(STAGE_LABELS.values())))
    sub.add_parser("generate", help="write pt-*.md agents from the profile")
    sub.add_parser("check", help="hint when generated agents are stale")
    args = ap.parse_args(argv)
    root = Path(args.root).resolve() if args.root else find_root()
    if args.cmd == "stage":
        return cmd_stage(root, args.key)
    if args.cmd == "generate":
        return cmd_generate(root)
    return cmd_check(root)


if __name__ == "__main__":
    sys.exit(main())
